### ISSUE TITLE
Develop lists before merge sharding-scaling into dev branch

### ISSUE THREAD

**Issue by KomachiSion** [apache/incubator-shardingsphere#3598]
Currently, ShardingScaling project has been merged into incubator-shardingsphere, as a sub-project in branch `sharding-scaling`.

But It's not enough to release, and can't merge to main branch `dev`. There are some things must be done, I think:

- [x] Refactor and enhance sharding-scaling-core #3602 
- [x] Need to be serviced and provide public interfaces #3256 
- [x] UI design and cooperation
- [x] Support PostgreSQL #3699
- [x] Add sharding-scaling-distribustion #3600 

If you have other important things you think need to add before merge to dev branch, please describe under this issue.

**Comment by ssxlulu** [comment]
Does data metrics have been included in the develop lists, like statistics about how much items have been read or writen, the total items have been migrated?

**Comment by KomachiSion** [comment]
> Does data metrics have been included in the develop lists, like statistics about how much items have been read or writen, the total items have been migrated?

It should be include in scaling progress I think.

**Comment by ssxlulu** [comment]
> > Does data metrics have been included in the develop lists, like statistics about how much items have been read or writen, the total items have been migrated?
> 
> It should be include in scaling progress I think.

Yes, I see the scaling progress item.I will submit a new issue and let's talk about it.
