### ISSUE TITLE
Optimization for Sharing Parser with ANTLR Visitor for MySQL

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#3914]
Hi folks, we would like to refactor existing parser engine with **ANTLR visitor** for better performance. It is scheduled as a long-term task and a big change for our 5.x release, **we would like to welcome anyone who is interested in it to join us for this wonderful sharding parser**! 😃 

> Take a look at the task detail below, you would learn it more. ⬇️ 

**Please follow up with your comment 📝 , if you want to join**!  What’s more, welcome your any comment and suggestion!

**Comment by tristaZero** [comment]
## Here is instruction

### Tasks:
1. Add rule visitors in `MySQLVisitor.java` based on g4 files[1].
2. Check whether rule name in g4 files is appropriate or not.
3. Add parsed integrated test for your **new main rule visitor**.

### Task detail:
1. Add rule visitors

1.1 Since `MySQLVisitor.java` extends `MySQLStatementBaseVisitor<ASTNode>.java`, you should overwrite `visitRuleName(ctx)` from `MySQLStatementBaseVisitor<ASTNode>` referring to rules in g4 files.
1.2 When adding `visitRuleName(ctx)`, you should put it below the corresponding note generally named `xxx.g4` and keep its order same with where it is in `xxx.g4` file.
1.3 What we need after parsing is those classes implement `SQLStatemnt` interface, so you should parse all necessary rules (add necessary rule visitors) making up `the main rules` in `MySQLStatement.g4`, and then fill necessary `segments` to `xxxSQLStatemnt`.


2.Check rule name

2.1 If we do not care one rule (do not add visitor for it), its name should end up with `_` in g4 file. For instance, we do not add visitor for `IDENTIFIER_` in `baseRule.g4`.
2.2 Otherwise this rule name should not contain `_` in the end.
2.3 If existing rule name does not accord with the above rules, please fix it.


3. Add parsed integrated test

When you successfully add `one main rule visitor`, adding parsed integrated test for it is necessary.

3.1 Copy sql case you need from `./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/sharding/` to `./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/visitor/` (`Please note to keep the same directory`). 
3.2 Copy the corresponding sql parsed result from `./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sharding/` to ` ./incubator-shardingsphere/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/visitor/` (`Please note to keep the same directory`).
3.3 Run `org.apache.shardingsphere.sql.parser.integrate.engine.visitor.VisitorParameterizedParsingTest`.
3.4 If there is no sql case you need in `./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/sharding/`, please record it to this issue[2]. P.S, my suggestion is to easily test its parsed result previously.


### Examples
1. Current functions in `org.apache.shardingsphere.sql.parser.MySQLVisitor` could provide examples for you.
2. You could learn more the parsed integrated test from test entrance `org.apache.shardingsphere.sql.parser.integrate.engine.visitor.VisitorParameterizedParsingTest`. 

### Notice
1. This guideline applys to `OracleVisitor`, `PostrgreSQLVisitor`, `SQLServerVisitor` and `SQL92Visitor` as well.

[1] DALStatement.g4, DCLStatement.g4, DDLStatement.g4, DMLStatement.g4, TCLStatement.g4 and StoreProcedure.g4
[2] https://github.com/apache/incubator-shardingsphere/issues/3967

**Comment by dongzl** [comment]
MySQL visitor progress: 
1. DAL
- [ ] reset
- [ ] set
- [ ] show
2. DCL
- [ ] alter-login
- [ ] alter-role
- [x] alter-user
- [ ] create-login
- [x] create-role
- [x] create-user
- [ ] deny-user
- [ ] drop-login
- [ ] drop-role
- [x] drop-user
- [ ] grant-user
- [x] rename-user
- [ ] revoke-user
- [ ] set-default-role
- [x] set-password
- [ ] set-role
3. DDL
- [ ] alter-index
- [x] alter-table
- [x] create-index
- [x] create-table
- [x] drop-index
- [x] drop-table
- [x] truncate
4. DML
- [x] delete
- [x] insert
- [ ] long-sql
- [ ] select
- [ ] select-aggregate
- [ ] select-expression
- [ ] select-group-by
- [ ] select-join
- [ ] select-or
- [ ] select-order-by
- [ ] select-pagination
- [ ] select-pagination-group-by-order-by
- [ ] select-sub-query
- [x] update
5. TCL
- [x] begin-transaction
- [x] commit
- [x] rollback
- [x] savepoint
- [x] set-auto-commit
- [x] set-transaction

**Comment by tristaZero** [comment]
Here are some remaining task from my position,

MySQL visitor progress: 
- DAL  **(In charge of @jingshanglu)**
  - [ ] Optimizations points from #4117
  - [ ] set
  - [ ] show
- DCL  **(in the charge of @tianbin1001 and @beijing-penguin)**
  - [ ] alter-login
  - [ ] alter-role
  - [ ] create-login
  - [ ] deny-user
  - [ ] drop-login
  - [ ] grant-user
  - [ ] revoke-user
  - [ ] set-role
- DDL  **(in the charge of @SteNicholas)**
  - [ ] Consider to simply `visitCreateTable` in `MySQLDDLVisitor`
  - [ ] Consider to simply `visitAlterTable` in `MySQLDDLVisitor`
  - [ ] Consider to simply `createColumnDefinitionSegment` in `MySQLDDLVisitor`
- DML **(in the charge of @tristaZero)**
  - [ ] long-sql
  - [ ] select
  - [ ] select-aggregate
  - [ ] select-expression
  - [ ] select-group-by
  - [ ] select-join
  - [ ] select-or
  - [ ] select-order-by
  - [ ] select-pagination
  - [ ] select-pagination-group-by-order-by
  - [ ] select-sub-query
- TCL **(in the charge of @dongzl )**
Congrats for you!

**Comment by beijing-penguin** [comment]
#4191

**Comment by beijing-penguin** [comment]
> 这是我的职位剩余的任务，
> 
> MySQL访问者进​​度：
> 
> * DAL   **（负责@jingshanglu）**
>   
>   * [ ] [＃4117的](https://github.com/apache/incubator-shardingsphere/pull/4117)优化点[](https://github.com/apache/incubator-shardingsphere/pull/4117)
>   * [ ]  组
>   * [ ]  节目
> * DCL   **（由@ tianbin1001和@ beijing-penguin负责）**
>   
>   * [ ]  更改登录
>   * [ ]  替代角色
>   * [ ]  创建登录
>   * [ ]  拒绝用户
>   * [ ]  登陆
>   * [ ]  授予用户
>   * [ ]  撤消用户
>   * [ ]  设定角色
> * DDL   **（由@SteNicholas负责）**
>   
>   * [x] 考虑到简单地`visitCreateTable`在`MySQLDDLVisitor`
>   * [x] 考虑到简单地`visitAlterTable`在`MySQLDDLVisitor`
>   * [x] 考虑到简单地`createColumnDefinitionSegment`在`MySQLDDLVisitor`
> * DML **（由@tristaZero负责）**
>   
>   * [ ]  长sql
>   * [ ]  选择
>   * [ ]  选择汇总
>   * [ ]  选择表达式
>   * [ ]  选择组
>   * [ ]  选择加入
>   * [ ]  选择或
>   * [ ]  选择顺序
>   * [ ]  选择分页
>   * [ ]  按顺序选择分页组
>   * [ ]  选择子查询
> * TCL **（由@dongzl负责）** 
>   恭喜您！

#4191

**Comment by tianbin1001** [comment]
Please assign this issue to me.

**Comment by tianbin1001** [comment]
add createuser dcl #4119

**Comment by tianbin1001** [comment]
add antlr visitor for MySQL DCLStatement  #4135

**Comment by tianbin1001** [comment]
add grant visitor for MySQL DCLStatement #4190

**Comment by tianbin1001** [comment]
grant visitor optimize #4214

**Comment by beijing-penguin** [comment]
add revoke DCL SQL visitor parse and test unit #4223

**Comment by tristaZero** [comment]
Hi, @dongzl @beijing-penguin @tianbin1001 @SteNicholas @jingshanglu 
Could you update the status of [status1](https://github.com/apache/incubator-shardingsphere/issues/3914#issuecomment-581108911) and [status2](https://github.com/apache/incubator-shardingsphere/issues/3914#issuecomment-583220969) if you have made some progress?

**Comment by beijing-penguin** [comment]
> Hi, @dongzl @beijing-penguin @tianbin1001 @SteNicholas @jingshanglu
> Could you update the status of [status1](https://github.com/apache/incubator-shardingsphere/issues/3914#issuecomment-581108911) and [status2](https://github.com/apache/incubator-shardingsphere/issues/3914#issuecomment-583220969) if you have made some progress?
> 
> p.s If you could not edit it, please be free to contact any committer.

hi，please make revoke-user and set-role complete

**Comment by tristaZero** [comment]
> revoke-user

Hi, thanks for your feedback, done.

**Comment by tristaZero** [comment]
Hi congrats to everyone, we basically finish the parser opimization for MySQL! 🥇 

The parser opimization for other databases is our next step and then we will consider transferring our sharding parser from old one to the one we are working, which seems a great challenge for us, go ahead!
