### ISSUE TITLE
Parsing more segments

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4671]
#### TODO
- RenameColumnSegment
    - [x] Instead of `columnName`, parse `ColumnNameSegment` as its member.

- ColumnAfterPositionSegment
    - [x] Instead of `columnName`, parse `ColumnNameSegment` as its member.

- ColumnPositionSegment
    - [x] Instead of `columnName`, parse `ColumnNameSegment` as its member.

- ColumnDefinitionSegment
    - [x] Instead of `columnName`, parse `ColumnNameSegment` as its member.

- ColumnDefinitionSegment
    - [x] Instead of `columnName`, parse `ColumnNameSegment` as its member.
    - [x] Instead of `dataType`, parse `DataTypeSegment` as its member.

### Notes
- Refer to `TableNameSegment` to create `ColumnNameSegment`.
- `ComparisonOperatorType`  is expected to be `enum`.

**Comment by jingshanglu** [comment]
I'll support

**Comment by jingshanglu** [comment]
There is ColumnSegment. ColumnSegment is refer by orthers, and is similar to ColumnNameSegment.I want  move ColumnSegment to  generic, and use ColumnSegment instead of ColumnNameSegment .How do you think? @tristaZero

**Comment by tristaZero** [comment]
Hi, The last one seems optional, and the second last is our end subtask.

**Comment by tristaZero** [comment]
All done, good job.
