### ISSUE TITLE
orchestration-refactoring phase 1

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#4681]
According to https://github.com/apache/incubator-shardingsphere/issues/4522 , orchestration-refactoring begin now.
1.orchestration-refactoring phase 1 tasks:
- [x]  1.1 refactoring for java8 and polish codes #4682 #4687 
- [x]  1.2 config domain object design (in progress) #4699 
- [x]  1.3 registry domain object design (in progress) #4699
