### ISSUE TITLE
orchestration-refactoring phase 2

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#4701]
According to #4522 & #4681 , orchestration-refactoring begin now.
2.orchestration-refactoring phase 2 tasks:
- [x]  2.1 center-configuration project #4699)
- [x]  Add configuration project
- [x]  Extract existing code to configuration project
- [x]  Improve unit tests
- [x]  2.2 other projects with 2.1 (#4699)
- [x]  sharding-jdbc-orchestration
- [x]  sharding-spring-boot-starter
- [x]  sharding-spring-namespache
- [x]  sharding-proxy-common/backend
- [x] sharding-ui (#4705)
- [x]  2.3 core-configuration project (#4733)
- [x]  Add configuration project
- [x]  Extract existing code to configuration project
- [x]  Improve unit tests
- [x]  2.4 other projects with 2.3
- [x]  sharding-jdbc-orchestration
- [x]  sharding-spring-boot-starter
- [x]  sharding-spring-namespache
- [x]  sharding-proxy-common/backend
- [x]  sharding-ui 

------
Other following tasks:
3. Examples&docs调整
4. Metadata design (todo)
