### ISSUE TITLE
Refactoring `SelectStatementTestCase` assertion

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#4763]
To assert subqueryTable well, it is prerequisite to refactor `SelectStatementTestCase`.

**Comment by tristaZero** [comment]
### TODO list
- [ ] Rename `ExpectedTable` to `ExpectedSimpleTable`
- [ ] Create `ExpectedTable` class
- [ ] Modify all the parsing assertion result
- [ ] Modify `SelectStatementTestCase`

**Comment by tristaZero** [comment]
I finished it, so closed this one.
