### ISSUE TITLE
Refactor LogicSchema #MetaDataCenter-phase-1

### ISSUE THREAD

**Issue by kimmking** [apache/incubator-shardingsphere#5008]
According to https://github.com/apache/incubator-shardingsphere/issues/4896, we will refactor LogicSchema and 5 sub class to uniform all metadata loading:

- [x] extract physical metadata field in proxy for 5 sub class (#5010)
- [x] decouple physical metadata&decorated metadata  (#5025 #5033)
- [x] process logic tables for ShardingSchema&ShardingMetaDataLoader(#5038)
- [x] use strategy class to refresh metadata for sharding-jdbc(#5019 #5034 #)
- [x] use strategy class to refresh metadata for sharding-proxy(#5048)
