### ISSUE TITLE
Support remove schema dynamically

### ISSUE THREAD

**Issue by menghaoranss** [apache/incubator-shardingsphere#5065]
For the second module `Remove schemas in sharding-ui` of issue #5043 , there are 3 steps: 

- [x] 1. Add `delete(key)` interface in `CenterRepository`  and implement it with zookeeper&etcd&nacos&apollo(#5101)
- [x] 2. Add unit tests(#5101)
- [x] 3. Add a button to remove schemas in sharding-ui(#5112)

**Comment by kimmking** [comment]
A tip: need check only one schema left, can't allow to remove it.

**Comment by menghaoranss** [comment]
> A tip: need check only one schema left, can't allow to remove it.

Got it, great advice!

**Comment by ssxlulu** [comment]
Some questions, remove the schema will also delete the actual schemas and the tables in the backend database?

**Comment by menghaoranss** [comment]
> Some questions, remove the schema will also delete the actual schemas and the tables in the backend database?

Just remove schema configuration in config center.
